version: '{build}'
branches:
  only:
  - /master$/
environment:
  COVERALLS_TOKEN:
    secure: LtsUOD+J5nCL+lQVKh9iIVgTu7Imgg7v4F5ME5J3PQJHH4Z0QkEKLsHKD4O3hX6H
install:
- echo %cd%
- cd .\appveyor
- echo %cd%
- powershell .\install-software.ps1
- cd ..
- echo %cd%
before_build:
- .\appveyor\dotnet\dotnet.exe restore
build_script:
- .\appveyor\dotnet\dotnet.exe build
test_script:
- echo %cd%
- cd .\appveyor
- echo %cd%
- .\generate-coverage.bat
on_success:
- echo %cd%
- .\upload-coverage.bat
